# -*- coding: utf-8 -*-
"""TexttoSpeech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qa_7hNvc-KMTGdatbA7BNRTYCg9fxGVP
"""

!pip install protobuf==4.21.5

!pip uninstall -y protobuf pyarrow

!pip uninstall -y pyarrow

!pip uninstall -y pyarrow
!pip install pyarrow==17.0.0

!pip install datasets
!pip install transformers
!pip install torch

!pip install datasets==2.0.0

!pip install pyarrow==14.0.1

!pip install pyarrow==14.0.1
!pip install datasets==2.0.0

!pip list | grep pyarrow
!pip list | grep datasets

!pip install transformers torch

!pip install transformers torchaudio

!pip install gtts

!pip install gradio pymupdf gtts

import gradio as gr
import fitz  # PyMuPDF
from gtts import gTTS

# Function to extract text from PDF
def extract_text_from_pdf(pdf_file):
    pdf_document = fitz.open(pdf_file.name)
    text = ""
    for page_num in range(len(pdf_document)):
        page = pdf_document.load_page(page_num)
        text += page.get_text()
    return text

# Function to convert text to speech and save as audio file
def text_to_speech_gtts(text):
    tts = gTTS(text=text, lang='en')
    audio_path = "output.mp3"
    tts.save(audio_path)
    return audio_path

# Gradio function
def pdf_to_speech(pdf_file):
    # Extract text from PDF
    pdf_text = extract_text_from_pdf(pdf_file)

    # Convert text to speech
    audio_path = text_to_speech_gtts(pdf_text)

    # Provide download link for the audio file
    return audio_path, "output.mp3"

# Create Gradio interface
iface = gr.Interface(
    fn=pdf_to_speech,
    inputs=gr.File(label="Upload PDF"),
    outputs=[gr.Audio(label="Generated Speech"), gr.File(label="Download Audio")],
    title="PDF to Speech Converter",
    description="Upload a PDF file, and get the text-to-speech conversion with a download option for the audio file."
)

# Launch the Gradio interface
iface.launch()